server:
  port: 7002
#  服务名
spring:
  application:
    name: service-aliyun-7002
    #环境设置：dev，test，prod
  profiles:
    active: dev
  servlet:
    multipart:
      # 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB
      # 最大上传单个文件大小：默认1M
      max-file-size: 1024MB
  #    nacos注册
  cloud:
    nacos:
      discovery:
        server-addr: 121.89.177.244:8848
  #redis数据库连接设置
  redis:
    host: 121.89.177.244
    port: 6379
    database: 0
    timeout: 1800000
    password: 22446688
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
#阿里云OSS
#不同服务器，地址不同
aliyun:
  oss:
   file:
    endpoint: oss-cn-chengdu.aliyuncs.com
    keyId: LTAI4GKbm3sbKrQutNLfpD6g
    keySercert: otsw0JVsvBW5hsBbmXn3lMN3ox1FiL
    bucketName: plxc

