spring:
  cloud:
    gateway:
      routes:
        - id: service-acl
          uri: lb://service-acl-8002
          predicates:
            - Path=/acl/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}
#        - id: blog-web
#          uri: lb://blog-web
#          predicates:
#            - Path=/**
    nacos:
      discovery:
        server-addr: 121.89.177.244:8848
server:
  port: 8888
