server:
  port: 7001
spring:
  application:
    name: service_center_7001
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.89.177.244:3306/club?useUnicode=true&characterEncoding=UTF-8
    password: 22446688
    username: root
  #redis数据库连接设置
  redis:
    host: 121.89.177.244
    port: 6379
    database: 0
    timeout: 1800000
    password: 22446688
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0

    #返回的json数据全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:MM:SS
    time-zone: GMT+8
#    nacos注册
  cloud:
    nacos:
      discovery:
        server-addr: 121.89.177.244:8848
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#  <!--#配置mapper xml文件路径-->,必须pom.xml进行配置后使用
#=================================

#开启熔断机制
feign:
  hystrix:
    enabled: true


#阿里云vod
#不同服务器，地址不同
aliyun:
  vod:
    file:
      keyid: LTAI4GKbm3sbKrQutNLfpD6g
      keysercert: otsw0JVsvBW5hsBbmXn3lMN3ox1FiL


